#config_version=6

switches:
    s_left_flipper:
        number: 0
        tags: left_flipper
    s_right_flipper:
        number: 1
        tags: right_flipper

coils:
    c_flipper_left_main:
        number: 0
    c_flipper_left_hold:
        number: 1
        allow_enable: true
    c_flipper_right_main:
        number: 2
    c_flipper_right_hold:
        number: 3
        allow_enable: true

playfields:
    playfield:
        tags: default
        default_source_device: None

flippers:
    left_flipper:
        main_coil: c_flipper_left_main
        hold_coil: c_flipper_left_hold
        activation_switch: s_left_flipper
    right_flipper:
        main_coil: c_flipper_right_main
        hold_coil: c_flipper_right_hold
        activation_switch: s_right_flipper
## MPF Main Machine Config File
#
# This file defines your system-wide properties like switches,
# drivers, ball devices, hardware platforms, and more. You can
# include everything here, or create sub-config files to be
# imported and merged with this one.


modes:
  - attract
  - base